openapi: 3.0.0
info:
  title: Datadog Events API
  version: 1.0.0
servers:
  - url: https://api.us3.datadoghq.com/
paths:
  /api/v2/events/{eventid}:
    get:
      summary: Get events
      operationId: getEvents
      parameters:
        - in: path
          name: eventid
          schema:
            type: string
          required: true
          description: ID of the Event
        - in: header
          required: true
          name: DD-APPLICATION-KEY
          schema:
            type: string
        - in: header
          name: Accept
          schema:
            type: string
          required: true
          description: Default is application/json  
      responses:
        '200':
          description: Successful response
