openapi: 3.0.0
info:
  title: Datadog Events API
  version: 1.0.0
servers:
  - url: https://api.us3.datadoghq.com/
paths:
  /api/v2/events/{eventid}:
    get:
      summary: Get specific event based on ID
      operationId: getSpecificEvent
      parameters:
        - in: path
          name: eventid
          schema:
            type: string
          required: true
          description: ID of the Event
        - in: header
          required: true
          name: DD-APPLICATION-KEY
          schema:
            type: string
        - in: header
          name: Accept
          schema:
            type: string
          required: true
          description: Default is application/json  
      responses:
        '200':
          description: Successful response
  /api/v2/events?page[limit]=5:
    get:
      summary: Get all events
      operationId: getAllEvents
      parameters:
        - in: header
          required: true
          name: DD-APPLICATION-KEY
          schema:
            type: string
        - in: header
          name: Accept
          schema:
            type: string
          required: true
          description: Default is application/json  
      responses:
        '200':
          description: Successful response
  /api/v2/logs/events/search:
    post:
      summary: Search logs events
      operationId: searchLogsEvents
      parameters:
        - in: header
          required: true
          name: DD-APPLICATION-KEY
          schema:
            type: string
        - in: header
          required: true
          name: DD-API-KEY
          schema:
            type: string
        - in: header
          name: Content-Type
          schema:
            type: string
          required: true
          description: Default is application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filter:
                  type: object
                  properties:
                    query:
                      type: string
                      description: The search query - see Datadog Logs Search Syntax documentation for details
                    from:
                      type: string
                      description: The start time for the query as an ISO 8601 datetime string
                    to:
                      type: string
                      description: The end time for the query as an ISO 8601 datetime string
                page:
                  type: object
                  properties:
                    limit:
                      type: integer
                      description: Maximum number of logs returned
                    cursor:
                      type: string
                      description: Cursor for paginating through results
      responses:
        '200':
          description: Successful response
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
